### PR TITLE
Improved markdown rendering with MarkdownExtra transform class

### PR DESCRIPTION
**Pull request by nlenkowski**
Hey there. First off, very useful plugin, thanks for putting it together. I came across it via [this nice writeup](https://deliciousbrains.com/wordpress-plugin-review-github-readme) on the Delicious Brains blog.

I did have some issues with [this Github readme](https://github.com/nlenkowski/blujay/blob/master/README.md) displaying inline code and code blocks incorrectly however. See attached screenshots comparing the Markdown vs MarkdownExtra transform and the issues should be apparent. Basically, the Markdown transform does not wrap code blocks in both `<pre>` and `<code>` tags as it should. So both inline code and code blocks are wrapped only in `<code>` tags, which causes problems when trying to style them differently. With MarkdownExtra enabled this is corrected and better styling is possible.
### Markdown

markdown
### MarkdownExtra

markdownextra

### CODE REVIEW

**Comment by octalmage** [comment]
Looks good to me! I'll test it and get it merged. 

Thanks!!

**Comment by nlenkowski** [comment]
:thumbsup:

**Comment by nlenkowski** [comment]
Hey there, just curious if you are planning on merging this? I've been using my own fork for awhile, but would love to use the official release.

**Comment by octalmage** [comment]
Yes! I honestly forgot about this, I'll get it released now.

**Comment by octalmage** [comment]
Looks like there are a few other places where Markdown needs to be replaced with MarkdownExtra, this is generating a fatal error. I'll get it fixed!

**Comment by nlenkowski** [comment]
No worries, and thanks for looking into it. I did pretty limited testing with the previous version only.

**Comment by octalmage** [comment]
The update has been released and it seems to be working well! Thanks again!

**Comment by nlenkowski** [comment]
Awesome. Just updated and its working great. Thanks as well!

**Pull request merged**
